AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Migracle Website Serverless Backend

Globals:
  Function:
    Timeout: 10
    MemorySize: 128
    Runtime: nodejs18.x
    Architectures:
      - x86_64
    Environment:
      Variables:
        REGION: us-west-2

Resources:
  # API Gateway
  MigracleApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      Cors:
        AllowMethods: "'GET,POST,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key'"
        AllowOrigin: "'*'"

  # Lambda Functions
  ContactFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/contact-handler/
      Handler: app.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ContactsTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref MigracleApi
            Path: /api/contact
            Method: post

  SubscribeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/subscribe-handler/
      Handler: app.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref SubscribersTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref MigracleApi
            Path: /api/subscribe
            Method: post

  # DynamoDB Tables
  ContactsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: migracle-contacts
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH

  SubscribersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: migracle-subscribers
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: email
          AttributeType: S
      KeySchema:
        - AttributeName: email
          KeyType: HASH

  # S3 Bucket for Website Hosting
  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub migracle-website-${AWS::AccountId}
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerPreferred
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - '*'
            AllowedMethods:
              - GET
              - HEAD
            AllowedOrigins:
              - '*'
            MaxAge: 3000

  WebsiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WebsiteBucket
      PolicyDocument:
        Statement:
          - Action:
              - s3:GetObject
            Effect: Allow
            Resource: !Sub arn:aws:s3:::${WebsiteBucket}/*
            Principal: '*'

  # CloudFront Distribution
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - DomainName: !GetAtt WebsiteBucket.RegionalDomainName
            Id: S3Origin
            CustomOriginConfig:
              OriginProtocolPolicy: http-only
              HTTPPort: 80
              HTTPSPort: 443
              OriginSSLProtocols:
                - TLSv1.2
        Enabled: true
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachedMethods:
            - GET
            - HEAD
            - OPTIONS
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
        PriceClass: PriceClass_100
        ViewerCertificate:
          CloudFrontDefaultCertificate: true
        CustomErrorResponses:
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html

Outputs:
  ApiEndpoint:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${MigracleApi}.execute-api.${AWS::Region}.amazonaws.com/prod"
  
  WebsiteURL:
    Description: "S3 Website URL"
    Value: !GetAtt WebsiteBucket.WebsiteURL
  
  CloudFrontURL:
    Description: "CloudFront Distribution URL"
    Value: !Sub "https://${CloudFrontDistribution.DomainName}"
